import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'utils/Responsive';
import {Colors} from 'colors/Colors';
export default StyleSheet.create({
  container: {
    backgroundColor: Colors.darkBlue,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
  },
  lunchTextView: {
    flexDirection: 'row',
    flex: 4,
    justifyContent: 'center',
    paddingTop: hp(0.5),
  },
  text1: {
    color: Colors.white,
    marginRight: wp(2),
    fontSize: 18,
    fontWeight: 'bold',
  },
  secondView: {
    backgroundColor: Colors.white,
    shadowOpacity: 0.1,
    top: hp(1),
    marginHorizontal: wp(2),
    paddingHorizontal: wp(2),
    paddingVertical: hp(2),
    display: 'flex',
  },
  dropDownView: {
    flexDirection: 'row',
    paddingVertical: hp(1),
    paddingHorizontal: wp(2),
    alignItems: 'center',
    zIndex: 1000,
  },
  thirdView: {
    flexDirection: 'row',
    paddingVertical: hp(1),
    paddingHorizontal: wp(2),
    alignItems: 'center',
    marginTop: hp(2),
  },
  fourthView: {
    borderRadius: 4,
    borderWidth: 1,
    width: wp(50),
    height: hp(4),
    justifyContent: 'center',
    alignItems: 'center',
  },
  fifthView: {
    flexDirection: 'row',
    paddingVertical: hp(1),
    paddingHorizontal: wp(2),
    alignItems: 'center',
  },
  sixthView: {
    borderRadius: 4,
    borderWidth: 1,
    width: wp(50),
    height: hp(4),
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitView: {
    backgroundColor: Colors.darkBlue,
    paddingVertical: hp(1.5),
    width: wp(50),
    marginHorizontal: wp(20),
  },
  buttomView: {
    backgroundColor: Colors.white,
    shadowOpacity: 0.1,
    top: hp(2),
    marginHorizontal: wp(2),
    paddingHorizontal: wp(2),
    paddingVertical: hp(2),
    display: 'flex',
    height: hp(52),
  },
  appliedView: {
    backgroundColor: Colors.lightGray,
    paddingVertical: hp(1.5),
    borderBottomWidth: 1,
  },
  appliedText: {
    color: Colors.customColor({r: 1, g: 98, b: 43}),
    fontWeight: 'bold',
    fontSize: 18,
    textAlign: 'center',
  },
  monthlyRequestView: {
    marginTop: hp(1),
    shadowOpacity: 0.4,
    borderRadius: 2,
    backgroundColor: Colors.lightGray,
  },
  monthlyView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
  },
  cancelView: {
    backgroundColor: Colors.red,
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(1),
    borderRadius: 4,
  },
  buttomTextView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(20),
    paddingVertical: hp(3),
  },
  buttomText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: Colors.lightBlue,
    marginRight: wp(5),
  },
  loaderContainer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9999,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Colors.black,
    opacity: 0.5,
  },
  selectedDated: {
    fontSize: 14,
  },
});
