import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'utils/Responsive';
import {Colors} from 'colors/Colors';
export default StyleSheet.create({
  container: {
    backgroundColor: Colors.darkBlue,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: wp(2),
    paddingVertical: hp(1.5),
  },
  textView: {
    flexDirection: 'row',
    flex: 2,
    // justifyContent: 'center',
    paddingTop: hp(0.5),
  },
  text1: {
    color: Colors.white,
    marginRight: wp(2),
    fontSize: 18,
    fontWeight: '500',
  },
  imageView: {
    height: 150,
    backgroundColor: Colors.lightBlue,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(3),
  },
  monthText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
    marginRight: wp(3),
  },
  labelView: {
    flexDirection: 'row',
    flex: 1,
    // justifyContent: 'space-between',
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(4),
  },
  earningView: {
    flexDirection: 'row',
    paddingVertical: hp(1),
    backgroundColor: Colors.lightBlue,
    borderRadius: 5,
    alignItems: 'center',
    paddingHorizontal: wp(3),
    justifyContent: 'space-between',
    marginVertical: hp(1),
  },
  minusImageView: {
    height: 25,
    width: 25,
    borderColor: 'white',
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  earningTextView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(4),
  },
  deductionView: {
    flexDirection: 'row',
    paddingVertical: hp(1),
    backgroundColor: Colors.lightBlue,
    borderRadius: 5,
    alignItems: 'center',
    paddingHorizontal: wp(3),
    justifyContent: 'space-between',
  },
  deductionImageView: {
    height: 25,
    width: 25,
    borderColor: 'white',
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deductionTextView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(4),
  },
});
